# General aliases

alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias tmux="TERM=screen-256color-bce tmux"
alias dev='./.dotfiles/tmux/tmuxcwd.sh dev 1'
alias dev1='./.dotfiles/tmux/tmuxcwd.sh dev1 1'
alias dev2='./.dotfiles/tmux/tmuxcwd.sh dev2 1'
alias runpy='./.dotfiles/tmux/tmuxcwd.sh runpy'
alias ..='cd ../../'
alias ...='cd ../../../'
